# Generated by Django 3.1.2 on 2020-11-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20201108_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
