airports = {
    "ABQ": "Albuquerque",
    "ACA": "Acapulco",
    "ACK": "Nantucket",
    "ACN": "Arches & Canyonlands",
    "ACY": "Atlantic City /Atlantic Cty",
    "ADL": "Adelaide",
    "AKL": "Auckland",
    "ALC": "Alicante",
    "AMS": "Amsterdam",
    "ANA": "Anaheim",
    "ANC": "Anchorage",
    "ANN": "Annapolis",
    "ANU": "Antigua",
    "APC": "Napa Valley",
    "APF": "Naples",
    "ARN": "Stockholm",
    "ASP": "Aspen",
    "ATH": "Athens",
    "ATL": "Atlanta",
    "AUA": "Aruba",
    "AUH": "Abu Dhabi",
    "AUS": "Austin",
    "AVL": "Asheville",
    "AXA": "Anguilla",
    "BCN": "Barcelona",
    "BDA": "Bermuda",
    "BER": "Berlin",
    "BKK": "Bangkok",
    "BNA": "Nashville",
    "BNE": "Brisbane",
    "BOC": "Boca Raton",
    "BOI": "Boise",
    "BOS": "Boston",
    "BRU": "Brussels",
    "BRY": "Bryce Canyon National Park",
    "BTR": "Baton Rouge",
    "BTV": "Burlington",
    "BUD": "Budapest",
    "BUE": "Buenos Aires",
    "BUF": "Buffalo",
    "BWI": "Baltimore",
    "BZE": "Belize City",
    "CAI": "Cairo",
    "CBS": "Cabo San Lucas",
    "CHA": "Charlottesville",
    "CHI": "Chicago",
    "CLE": "Cleveland",
    "CLT": "Charlotte",
    "CMH": "Columbus",
    "COL": "Colorado Springs",
    "CPH": "Copenhagen",
    "CPT": "Cape Town",
    "CRP": "Corpus-Christi",
    "CRW": "Charleston",
    "CTN": "Chattanooga",
    "CUN": "Cancun",
    "CVG": "Cincinnati",
    "CZM": "Cozumel",
    "DEN": "Denver",
    "DFW": "Dallas",
    "DSM": "Des Moines",
    "DTW": "Detroit",
    "DUB": "Dublin",
    "DXB": "Dubai",
    "EDI": "Edinburgh",
    "EGE": "Vail",
    "ELP": "El Paso",
    "FAI": "Fairbanks",
    "FLG": "Flagstaff",
    "FLL": "Fort Lauderdale",
    "FMY": "Fort Myers",
    "FNL": "Fort Collins",
    "GCN": "Grand Canyon",
    "GLA": "Glasgow",
    "GLS": "Galveston",
    "GND": "Grenada",
    "GNP": "Glacier National Park",
    "GPS": "Galapagos",
    "GRR": "Grand Rapids",
    "GSP": "Greenville",
    "GTN": "Grand Teton National Park",
    "GTY": "Gettysburg",
    "GVA": "Geneva",
    "GWY": "Galway",
    "HAM": "Hamburg",
    "HAV": "Havana",
    "HHH": "Hilton Head",
    "HKG": "Hong Kong",
    "HKT": "Phuket",
    "HNL": "Honolulu",
    "HOU": "Houston",
    "IBZ": "Ibiza",
    "IND": "Indianapolis",
    "IST": "Istanbul",
    "JAC": "Jackson Hole",
    "JAX": "Jacksonville",
    "JCA": "Cannes",
    "JNB": "Johannesburg",
    "JRA": "New York City",
    "JTR": "Santorini",
    "KNX": "Knoxville",
    "KRK": "Krakow",
    "KYL": "Key Largo",
    "LAS": "Las Vegas",
    "LAX": "Los Angeles",
    "LGB": "Long Beach",
    "LIH": "Kauai",
    "LIM": "Lima",
    "LIS": "Lisbon",
    "LIT": "Little Rock",
    "LON": "London",
    "LOU": "Louisville",
    "LTH": "Lake Tahoe",
    "LXR": "Luxor",
    "MAD": "Madrid",
    "MAN": "Manchester",
    "MEL": "Melbourne",
    "MEM": "Memphis",
    "MEX": "Mexico City",
    "MIA": "Miami",
    "MIL": "Milan",
    "MKC": "Kansas City",
    "MKE": "Milwaukee",
    "MOW": "Moscow",
    "MSN": "Madison",
    "MSY": "New Orleans",
    "MVY": "Martha's Vineyard",
    "MYR": "Myrtle Beach",
    "NAP": "Naples",
    "NCE": "Nice",
    "OAX": "Oaxaca",
    "OKC": "Oklahoma City",
    "OMA": "Omaha",
    "ORL": "Orlando",
    "OSL": "Oslo",
    "OYS": "Yosemite",
    "PAR": "Paris",
    "PCB": "Panama City Beach",
    "PEK": "Beijing",
    "PER": "Perth",
    "PHX": "Phoenix",
    "PIE": "Tampa",
    "PIT": "Pittsburgh",
    "PNS": "Pensacola",
    "PDX": "Portland",
    "PRG": "Prague",
    "PSP": "Palm Springs",
    "PUJ": "Punta Cana",
    "PVR": "Puerto Vallarta",
    "RAK": "Marrakech",
    "RDU": "Raleigh",
    "REY": "Reykjavik",
    "RIC": "Richmond",
    "RIO": "Rio de Janeiro",
    "RNO": "Reno",
    "ROM": "Rome",
    "SAF": "Santa Fe",
    "SAN": "San Diego",
    "SAO": "Sao Paulo",
    "SAT": "San Antonio",
    "SAV": "Savannah",
    "SBA": "Santa Barbara",
    "SBS": "Steamboat Springs",
    "SCL": "Santiago ",
    "SDQ": "Santo Domingo",
    "SEA": "Seattle",
    "SEL": "Seoul",
    "SFN": "Santa Fe",
    "SFO": "San Francisco",
    "SHA": "Shanghai",
    "SIN": "Singapore",
    "SJC": "San Jose",
    "SLC": "Salt Lake City",
    "SMF": "Sacramento",
    "SYD": "Sydney",
    "SZG": "Salzburg",
    "TAB": "Tobago",
    "TLH": "Tallahassee",
    "TLV": "Tel Aviv",
    "TPA": "Tampa",
    "TUL": "Tulsa",
    "TUS": "Tucson",
    "TYO": "Tokyo",
    "UKY": "Kyoto",
    "UST": "St.Augustine",
    "UVF": "St. Lucia",
    "YBA": "Banff",
    "YMQ": "Montreal",
    "YOW": "Ottawa",
    "YQB": "Quebec City",
    "YVR": "Vancouver",
    "YYC": "Calgary",
    "YYZ": "Toronto",
    "ZIO": "Zion National Park",
    "ZRH": "Zurich"
}


def convert_city_to_IATA(city):
    for iata, location in airports.items():
        if location == city:
            return iata
    return "Not Found"
