# Generated by Django 3.1.2 on 2020-10-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='DestinationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.destination')),
            ],
        ),
    ]
