# Generated by Django 3.1.2 on 2020-10-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201025_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationitem',
            old_name='todolist',
            new_name='destination',
        ),
    ]
