# Generated by Django 3.1.2 on 2020-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20201025_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='todolist',
            new_name='destination',
        ),
    ]
