# Generated by Django 3.1.2 on 2020-10-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20201025_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.destination'),
        ),
    ]
