# Generated by Django 3.1.2 on 2020-10-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20201025_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('star_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=200)),
                ('destinationID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
