# Generated by Django 3.1.2 on 2020-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20201025_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(default='rocks and water', max_length=200),
        ),
    ]
