# Generated by Django 3.1.2 on 2020-10-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20201025_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='destinationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.destination'),
        ),
    ]
